apiVersion: v1
entries:
  replicator:
  - apiVersion: v2
    created: "2025-08-15T12:57:39.631911215Z"
    description: Helm chart for replicator
    digest: c396125b2e96ec1573eccd56eed4d5002c884d79958c3d51528fd4342d1c08aa
    name: replicator
    urls:
    - https://jamesw-xml.github.io/replicator/charts/replicator-0.1.0.tgz
    version: 0.1.0
generated: "2025-08-15T12:57:39.631179016Z"
