{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: replicator
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host | default "replicator.local" }}
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: replicator
                port:
                  number: 5000
{{- end }}
