apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ template "replicator.name" . }}
    chart: {{ template "replicator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.pvc.name | default template "replicator.fullname" }}
spec:
  accessModes:
    {{- toYaml .Values.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "1Mi" }}
  {{ if .Values.pvc.storageClass }}
  storageClassName: {{ .Values.pvc.storageClass }}
  {{ end }}