apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port | default 5000 }}
      targetPort: {{ .Values.deployment.containerPort | default 5000 }}
  selector:
    app: {{ .Values.labels.app | default "replicator" }}
