name: Build and Push Docker Image
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'charts/replicator/values.yaml'
      - 'charts/replicator/Chart.yaml'
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/pr-build-test.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest semantic version tag
        id: get_tag
        run: |
            echo "Fetching all tags..."
            git fetch --tags --force
            echo "Checking for latest tag..."
            echo $(git tag --list)
            latest_tag=$(git tag --list --sort=-v:refname | grep -E '^([0-9]+\.){2}[0-9]+$' | head -n 1)
            if [ -z "$latest_tag" ]; then
              echo "tag=0.0.1" >> $GITHUB_OUTPUT
            else
              IFS='.' read -r major minor patch <<< "$latest_tag"
              patch=$((patch+1))
              echo "tag=${major}.${minor}.${patch}" >> $GITHUB_OUTPUT
            fi
      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          if docker manifest inspect ghcr.io/${{ github.repository }}/replicator:${IMAGE_TAG} > /dev/null 2>&1; then
            echo "Image already exists, skipping build."
            exit 0
          fi
          docker build -t ghcr.io/${{ github.repository }}/replicator:${IMAGE_TAG} -f Dockerfile .
          docker push ghcr.io/${{ github.repository }}/replicator:${IMAGE_TAG}
      - name: Update Helm values.yaml with new image tag
        env:
          IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          sed -i 's/tag: .*/tag: "'${IMAGE_TAG}'"/' charts/replicator/values.yaml
          cat charts/replicator/values.yaml
      - name: Update Chart.yaml version
        env:
            CHART_VERSION: ${{ steps.get_tag.outputs.tag }}
        run: |
            sed -i 's/^version: .*/version: \"'${CHART_VERSION}'\"/' charts/replicator/Chart.yaml
            sed -i 's/^appVersion: .*/appVersion: \"'${CHART_VERSION}'\"/' charts/replicator/Chart.yaml
            cat charts/replicator/Chart.yaml
      - name: Commit and push updated values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git commit -am "Update image tag to ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          git push origin master

      - name: Merge HEAD into master
        run: |
          git fetch origin master
          git checkout master
          git merge --ff-only HEAD

      - name: Create and push new tag from master
        run: |
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}
  publish-helm:
    uses: ./.github/workflows/helm-publish.yml
    needs: build-and-push
     